from enum import Enum

class PipelineState(str, Enum):
    REFERRAL_RECEIVED = "REFERRAL_RECEIVED"
    INTAKE_COMPLETE = "INTAKE_COMPLETE"
    ASSESSMENT_COMPLETE = "ASSESSMENT_COMPLETE"
    ELIGIBILITY_VERIFIED = "ELIGIBILITY_VERIFIED"
    AUTH_PENDING = "AUTH_PENDING"
    AUTH_APPROVED = "AUTH_APPROVED"
    READY_TO_SCHEDULE = "READY_TO_SCHEDULE"
    
